languageCode = "en-US"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
baseUrl = "https://thect.tw"
title = "Thect Blog"
theme = "anubis"
paginate = 10.0
enableRobotsTXT = true
summaryLength = 1

[menu]

	[[menu.main]]
	identifier = "posts"
	name = "[文章 / Posts]"
	title = "文章列表"
	url = "/posts/"
	weight = -1000

	[[menu.main]]
	identifier = "about"
	name = "[關於 / About]"
	title = "關於"
	url = "/about"
	weight = -50

	[[menu.main]]
	identifier = "youtube"
	name = "[Youtube]"
	post = "youtube"
	title = "Youtube"
	url = "https://youtube.com/thect"
	weight = -30

	[[menu.main]]
	identifier = "github"
	name = "[Github]"
	title = "Github"
	url = "https://github.com/cheetosysst"
	weight = -20

	[[menu.main]]
	identifier = "faq"
	name = "[FAQ]"
	title = "文章列表"
	url = "/faq"
	weight = -10

	[[main.main]]
	identifier = "rss"
	name = "[RSS]"
	title = "RSS"
	url = "/index.xml"
	weight = "-5"


[params]
author = "Chen Chang"
description = "Thect 的部落格，分享個人研究、心得、或單純發廢文的地方"
images = [
	"images/Thect_Small.jpg"
]
customCSS = [
	"css/my.css"
]
customJS = [
	"js/main.js"
]
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "dark-without-switcher"
readMore = true


[taxonomies]
category = "categories"
tag = "tags"

[markup]

	[markup.goldmark]

		[markup.goldmark.renderer]
		unsafe = true